server:
  port: ${port:8080}

spring:
  application:
    name: service
  profiles:
    active: cloud
  zipkin:
    enabled: false
    baseUrl: http://zipkin:9411/
    sender:
      type: web

management:
  endpoints:
    web:
      exposure:
        include: '*'

config:
  key: value
