server:
    port: 8443
    ssl:
        key-store: classpath:keystore.jks
        key-store-password: secret
        key-password: secret

keycloak:
  realm: springbootjaxrs
  realmKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwC+AqVatmVALRwYvjrRGB55+2c2d8KWkkKsviT0iwh67BuU17Pk+gjMSKFf7dkl+NL6/qIll5enu8LOjCacghWHBP/svC2fs/IogpeTHaGot8omw+04qU29dW432juDgf2QNnAswS2cw7EGBECAX8WIKVC8DIGxCN2OMMwjMzGGBw4NmHm+5un03nR4+DF2joRjGLxSUlILNZ165wQAK8bMrDDQ9QtAgXXUnbq4PvZvJR+xVP8s3eliC3HVi4NT8spFdyXdVpsMqrR+KLLbrRomirbbK70bXIIir1fp1/UMS+Ps/LqbduW7k0DBf66BtLsuUOW7evwUBIdVcbnokKQIDAQAB
  bearer-only: true
  auth-server-url: http://localhost:9080/auth
  ssl-required: external
  resource: client
  use-resource-role-mappings: true
  securityConstraints[0]:
      securityCollections[0]:
          name: api
          authRoles:
              - api
          patterns:
              - /api/*