name: test-documentation

on:
  pull_request:
    branches: [main]

jobs:
  gh-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: documentation
    steps:
      - uses: actions/checkout@v3.0.1
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
